# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += 1MissionPlan/1MissionPlan.pro \
        1MissionPlan_Subscriber/1MissionPlan_Subscriber.pro \
	2GetDroneScanRoute/2GetDroneScanRoute.pro \
	3DroneScanRoute/3DroneScanRoute.pro \
	4PlatformLocation/4PlatformLocation.pro \
	5StartJpegGeneration/5StartJpegGeneration.pro \
	6ReportJpegGeneration/6ReportJpegGeneration.pro \
        91UploadCurrModel/91UploadCurrModel.pro \
        92UploadDiffModel/92UploadDiffModel.pro \
	14RequestRefModel/14RequestRefModel.pro \
        15EndMission/15EndMission.pro
